ENGINE_REPO="The-DresOS-Foundation/DresOS-WebView"
ENGINE_CERT_SHA256="b7815f746c3183c66cad631079cb669c0494a8be542a2a96e5975d8fabcd92de"

AOSMIUM_REPO="AXP-OS/app_aosmium"
AOSMIUM_ASSET="webview32-signed.apk"
AOSMIUM_CERT_SHA256="005c9805d501bf50c1a8bfd3204b6908843088581fdcf3db8ab4f688ffc0e7b6"
AOSMIUM_HOME="https://codeberg.org/AXP-OS/app_aosmium/releases"
